# Generated by Django 2.1.2 on 2018-10-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='now',
            name='userID',
        ),
        migrations.AddField(
            model_name='user',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='foge', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Now',
        ),
    ]
