# Generated by Django 2.1.2 on 2018-10-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20181012_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
    ]
