# Generated by Django 2.1.2 on 2018-10-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_remove_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='update',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='foge', max_length=10),
        ),
    ]
